/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('@jtclarkjr/component-library-vue')['Button']
    Card: typeof import('@jtclarkjr/component-library-vue')['Card']
    Dialog: typeof import('@jtclarkjr/component-library-vue')['Dialog']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spinner: typeof import('@jtclarkjr/component-library-vue')['Spinner']
  }
}
